Employee.create(
    [
        {
            username: 'alex',
            email: 'alex@abc.com',
            first_name: 'Alex',
            last_name: 'Duan',
            password: 'alexrules',
            password_confirmation: 'alexrules',
            is_admin: true,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 7
        },
        {
            username: 'max',
            email: 'max@abc.com',
            first_name: 'Max',
            last_name: 'Brailovsky',
            password: 'maximumax',
            password_confirmation: 'maximumax',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 3
        },
        {
            username: 'chris',
            email: 'chris@abc.com',
            first_name: 'Chris',
            last_name: 'Sterritt',
            password: 'letmein',
            password_confirmation: 'letmein',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'fred.smith',
            email: 'fred.smith@abc.com',
            first_name: 'fred',
            last_name: 'smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'fred.jones',
            email: 'fred.jones@abc.com',
            first_name: 'fred',
            last_name: 'jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'fred.tate',
            email: 'fred.tate@abc.com',
            first_name: 'fred',
            last_name: 'tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'fred.cote',
            email: 'fred.cote@abc.com',
            first_name: 'fred',
            last_name: 'cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'fred.trimble',
            email: 'fred.trimble@abc.com',
            first_name: 'fred',
            last_name: 'trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'fred.broder',
            email: 'fred.broder@abc.com',
            first_name: 'fred',
            last_name: 'broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'john.smith',
            email: 'john.smith@abc.com',
            first_name: 'john',
            last_name: 'smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'john.jones',
            email: 'john.jones@abc.com',
            first_name: 'john',
            last_name: 'jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'john.tate',
            email: 'john.tate@abc.com',
            first_name: 'john',
            last_name: 'tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'john.cote',
            email: 'john.cote@abc.com',
            first_name: 'john',
            last_name: 'cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'john.trimble',
            email: 'john.trimble@abc.com',
            first_name: 'john',
            last_name: 'trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'john.broder',
            email: 'john.broder@abc.com',
            first_name: 'john',
            last_name: 'broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jane.smith',
            email: 'jane.smith@abc.com',
            first_name: 'jane',
            last_name: 'smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jane.jones',
            email: 'jane.jones@abc.com',
            first_name: 'jane',
            last_name: 'jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jane.tate',
            email: 'jane.tate@abc.com',
            first_name: 'jane',
            last_name: 'tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jane.cote',
            email: 'jane.cote@abc.com',
            first_name: 'jane',
            last_name: 'cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jane.trimble',
            email: 'jane.trimble@abc.com',
            first_name: 'jane',
            last_name: 'trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jane.broder',
            email: 'jane.broder@abc.com',
            first_name: 'jane',
            last_name: 'broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sandy.smith',
            email: 'sandy.smith@abc.com',
            first_name: 'sandy',
            last_name: 'smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sandy.jones',
            email: 'sandy.jones@abc.com',
            first_name: 'sandy',
            last_name: 'jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sandy.tate',
            email: 'sandy.tate@abc.com',
            first_name: 'sandy',
            last_name: 'tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sandy.cote',
            email: 'sandy.cote@abc.com',
            first_name: 'sandy',
            last_name: 'cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sandy.trimble',
            email: 'sandy.trimble@abc.com',
            first_name: 'sandy',
            last_name: 'trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sandy.broder',
            email: 'sandy.broder@abc.com',
            first_name: 'sandy',
            last_name: 'broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'tom.smith',
            email: 'tom.smith@abc.com',
            first_name: 'tom',
            last_name: 'smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'tom.jones',
            email: 'tom.jones@abc.com',
            first_name: 'tom',
            last_name: 'jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'tom.tate',
            email: 'tom.tate@abc.com',
            first_name: 'tom',
            last_name: 'tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'tom.cote',
            email: 'tom.cote@abc.com',
            first_name: 'tom',
            last_name: 'cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'tom.trimble',
            email: 'tom.trimble@abc.com',
            first_name: 'tom',
            last_name: 'trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'tom.broder',
            email: 'tom.broder@abc.com',
            first_name: 'tom',
            last_name: 'broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'bill.smith',
            email: 'bill.smith@abc.com',
            first_name: 'bill',
            last_name: 'smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'bill.jones',
            email: 'bill.jones@abc.com',
            first_name: 'bill',
            last_name: 'jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'bill.tate',
            email: 'bill.tate@abc.com',
            first_name: 'bill',
            last_name: 'tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'bill.cote',
            email: 'bill.cote@abc.com',
            first_name: 'bill',
            last_name: 'cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'bill.trimble',
            email: 'bill.trimble@abc.com',
            first_name: 'bill',
            last_name: 'trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'bill.broder',
            email: 'bill.broder@abc.com',
            first_name: 'bill',
            last_name: 'broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'alan.smith',
            email: 'alan.smith@abc.com',
            first_name: 'alan',
            last_name: 'smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'alan.jones',
            email: 'alan.jones@abc.com',
            first_name: 'alan',
            last_name: 'jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'alan.tate',
            email: 'alan.tate@abc.com',
            first_name: 'alan',
            last_name: 'tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'alan.cote',
            email: 'alan.cote@abc.com',
            first_name: 'alan',
            last_name: 'cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'alan.trimble',
            email: 'alan.trimble@abc.com',
            first_name: 'alan',
            last_name: 'trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'alan.broder',
            email: 'alan.broder@abc.com',
            first_name: 'alan',
            last_name: 'broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jill.smith',
            email: 'jill.smith@abc.com',
            first_name: 'jill',
            last_name: 'smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jill.jones',
            email: 'jill.jones@abc.com',
            first_name: 'jill',
            last_name: 'jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jill.tate',
            email: 'jill.tate@abc.com',
            first_name: 'jill',
            last_name: 'tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jill.cote',
            email: 'jill.cote@abc.com',
            first_name: 'jill',
            last_name: 'cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jill.trimble',
            email: 'jill.trimble@abc.com',
            first_name: 'jill',
            last_name: 'trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'jill.broder',
            email: 'jill.broder@abc.com',
            first_name: 'jill',
            last_name: 'broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'ann.smith',
            email: 'ann.smith@abc.com',
            first_name: 'ann',
            last_name: 'smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'ann.jones',
            email: 'ann.jones@abc.com',
            first_name: 'ann',
            last_name: 'jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'ann.tate',
            email: 'ann.tate@abc.com',
            first_name: 'ann',
            last_name: 'tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'ann.cote',
            email: 'ann.cote@abc.com',
            first_name: 'ann',
            last_name: 'cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'ann.trimble',
            email: 'ann.trimble@abc.com',
            first_name: 'ann',
            last_name: 'trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'ann.broder',
            email: 'ann.broder@abc.com',
            first_name: 'ann',
            last_name: 'broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sue.smith',
            email: 'sue.smith@abc.com',
            first_name: 'sue',
            last_name: 'smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sue.jones',
            email: 'sue.jones@abc.com',
            first_name: 'sue',
            last_name: 'jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sue.tate',
            email: 'sue.tate@abc.com',
            first_name: 'sue',
            last_name: 'tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sue.cote',
            email: 'sue.cote@abc.com',
            first_name: 'sue',
            last_name: 'cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sue.trimble',
            email: 'sue.trimble@abc.com',
            first_name: 'sue',
            last_name: 'trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
        {
            username: 'sue.broder',
            email: 'sue.broder@abc.com',
            first_name: 'sue',
            last_name: 'broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
            kudo_balance: 10,
            kudos_received: 0
        },
    ])

alex  = Employee.where(username: 'alex').first
max   = Employee.where(username: 'max').first
chris = Employee.where(username: 'chris').first
KudoTransaction.create(
    [
        {
            from: chris,
            to: alex,
            amount: 3,
        },
        {
            from: max,
            to: alex,
            amount: 1,
        },
        {
            from: alex,
            to: max,
            amount: 2,
        },
        {
            from: alex,
            to: max,
            amount: 1,
            created_at: 1.month.ago,
            updated_at: 1.month.ago,
        },
        {
            from: max,
            to: alex,
            amount: 3,
            created_at: 1.month.ago,
            updated_at: 1.month.ago,
        }
    ]
)
