Employee.create(
    [
        {
            username: 'alex',
            email: 'alex@abc.com',
            first_name: 'Alex',
            middle_initial: 'M',
            last_name: 'Duan',
            password: 'alexrules',
            password_confirmation: 'alexrules',
            is_admin: true,
            is_active: true,
        },
        {
            username: 'max',
            email: 'max@abc.com',
            first_name: 'Max',
            middle_initial: 'M',
            last_name: 'Brailovsky',
            password: 'maximumax',
            password_confirmation: 'maximumax',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'chris',
            email: 'chris@abc.com',
            first_name: 'Chris',
            middle_initial: 'M',
            last_name: 'Sterritt',
            password: 'letmein',
            password_confirmation: 'letmein',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'fred.smith',
            email: 'fred.smith@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'fred.jones',
            email: 'fred.jones@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'fred.tate',
            email: 'fred.tate@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'fred.cote',
            email: 'fred.cote@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'fred.trimble',
            email: 'fred.trimble@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'fred.broder',
            email: 'fred.broder@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'john.smith',
            email: 'john.smith@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'john.jones',
            email: 'john.jones@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'john.tate',
            email: 'john.tate@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'john.cote',
            email: 'john.cote@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'john.trimble',
            email: 'john.trimble@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'john.broder',
            email: 'john.broder@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jane.smith',
            email: 'jane.smith@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jane.jones',
            email: 'jane.jones@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jane.tate',
            email: 'jane.tate@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jane.cote',
            email: 'jane.cote@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jane.trimble',
            email: 'jane.trimble@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jane.broder',
            email: 'jane.broder@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sandy.smith',
            email: 'sandy.smith@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sandy.jones',
            email: 'sandy.jones@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sandy.tate',
            email: 'sandy.tate@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sandy.cote',
            email: 'sandy.cote@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sandy.trimble',
            email: 'sandy.trimble@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sandy.broder',
            email: 'sandy.broder@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'tom.smith',
            email: 'tom.smith@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'tom.jones',
            email: 'tom.jones@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'tom.tate',
            email: 'tom.tate@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'tom.cote',
            email: 'tom.cote@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'tom.trimble',
            email: 'tom.trimble@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'tom.broder',
            email: 'tom.broder@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'bill.smith',
            email: 'bill.smith@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'bill.jones',
            email: 'bill.jones@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'bill.tate',
            email: 'bill.tate@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'bill.cote',
            email: 'bill.cote@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'bill.trimble',
            email: 'bill.trimble@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'bill.broder',
            email: 'bill.broder@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'alan.smith',
            email: 'alan.smith@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'alan.jones',
            email: 'alan.jones@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'alan.tate',
            email: 'alan.tate@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'alan.cote',
            email: 'alan.cote@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'alan.trimble',
            email: 'alan.trimble@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'alan.broder',
            email: 'alan.broder@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jill.smith',
            email: 'jill.smith@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jill.jones',
            email: 'jill.jones@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jill.tate',
            email: 'jill.tate@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jill.cote',
            email: 'jill.cote@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jill.trimble',
            email: 'jill.trimble@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'jill.broder',
            email: 'jill.broder@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'ann.smith',
            email: 'ann.smith@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'ann.jones',
            email: 'ann.jones@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'ann.tate',
            email: 'ann.tate@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'ann.cote',
            email: 'ann.cote@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'ann.trimble',
            email: 'ann.trimble@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'ann.broder',
            email: 'ann.broder@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sue.smith',
            email: 'sue.smith@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sue.jones',
            email: 'sue.jones@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sue.tate',
            email: 'sue.tate@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sue.cote',
            email: 'sue.cote@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sue.trimble',
            email: 'sue.trimble@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            username: 'sue.broder',
            email: 'sue.broder@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
    ])

alex  = Employee.where(username: 'alex').first
max   = Employee.where(username: 'max').first
chris = Employee.where(username: 'chris').first
KudoTransaction.create(
    [
        {
            from: chris,
            to: alex,
            amount: 3,
        },
        {
            from: max,
            to: alex,
            amount: 1,
        },
        {
            from: alex,
            to: max,
            amount: 2,
        },
        {
            from: alex,
            to: max,
            amount: 1,
            created_at: 1.month.ago,
            updated_at: 1.month.ago,
        },
        {
            from: max,
            to: alex,
            amount: 3,
            created_at: 1.month.ago,
            updated_at: 1.month.ago,
        }
    ]
)
