Employee.create(
    [
        {
            email: 'alex@abc.com',
            first_name: 'Alex',
            middle_initial: 'M',
            last_name: 'Duan',
            password: 'alexrules',
            password_confirmation: 'alexrules',
            is_admin: true,
            is_active: true,
        },
        {
            email: 'max@abc.com',
            first_name: 'Max',
            middle_initial: 'M',
            last_name: 'Brailovsky',
            password: 'maximumax',
            password_confirmation: 'maximumax',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'chris@abc.com',
            first_name: 'Chris',
            middle_initial: 'M',
            last_name: 'Sterritt',
            password: 'letmein',
            password_confirmation: 'letmein',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'fred.smith@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'fred.jones@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'fred.tate@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'fred.cote@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'fred.trimble@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'fred.broder@abc.com',
            first_name: 'Fred',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'john.smith@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'john.jones@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'john.tate@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'john.cote@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'john.trimble@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'john.broder@abc.com',
            first_name: 'John',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jane.smith@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jane.jones@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jane.tate@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jane.cote@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jane.trimble@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jane.broder@abc.com',
            first_name: 'Jane',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sandy.smith@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sandy.jones@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sandy.tate@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sandy.cote@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sandy.trimble@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sandy.broder@abc.com',
            first_name: 'Sandy',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'tom.smith@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'tom.jones@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'tom.tate@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'tom.cote@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'tom.trimble@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'tom.broder@abc.com',
            first_name: 'Tom',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'bill.smith@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'bill.jones@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'bill.tate@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'bill.cote@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'bill.trimble@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'bill.broder@abc.com',
            first_name: 'Bill',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'alan.smith@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'alan.jones@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'alan.tate@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'alan.cote@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'alan.trimble@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'alan.broder@abc.com',
            first_name: 'Alan',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jill.smith@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jill.jones@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jill.tate@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jill.cote@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jill.trimble@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'jill.broder@abc.com',
            first_name: 'Jill',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'ann.smith@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'ann.jones@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'ann.tate@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'ann.cote@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'ann.trimble@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'ann.broder@abc.com',
            first_name: 'Ann',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sue.smith@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Smith',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sue.jones@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Jones',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sue.tate@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Tate',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sue.cote@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Cote',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sue.trimble@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Trimble',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
        {
            email: 'sue.broder@abc.com',
            first_name: 'Sue',
            middle_initial: 'M',
            last_name: 'Broder',
            password: 'asdfasdf',
            password_confirmation: 'asdfasdf',
            is_admin: false,
            is_active: true,
        },
    ])

alex   = Employee.where(email: 'alex@abc.com').first
max   = Employee.where(email: 'max@abc.com').first
chris   = Employee.where(email: 'chris@abc.com').first
KudoTransaction.create(
    [
        {
            from: chris,
            to: alex,
            amount: 3,
        },
        {
            from: max,
            to: alex,
            amount: 1,
        },
        {
            from: alex,
            to: max,
            amount: 2,
        },
        {
            from: alex,
            to: max,
            amount: 1,
            created_at: 1.month.ago,
            updated_at: 1.month.ago,
        },
        {
            from: max,
            to: alex,
            amount: 3,
            created_at: 1.month.ago,
            updated_at: 1.month.ago,
        }
    ]
)
